# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shellpad Interactive
email: shellpadinteractive@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio website for freelance software and game programmer company Shellpad Interactive.
baseurl: "https://gbeuneker.gitlab.io/Shellpad_Interactive"
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--content-->

# Build settings
markdown: kramdown